<?php

namespace App;

class ConfigGenerator {
    private $db;
    
    // Output paths mapped in docker container
    private $bindOptionsPath = '/data/bind/named.conf.options';
    private $bindLocalPath   = '/data/bind/named.conf.local';
    private $bindZonesDir    = '/data/bind/zones';
    private $dnsmasqConfPath = '/data/dnsmasq/dhcp.conf';
    private $chronyConfPath  = '/data/chrony/chrony.conf';
    private $sambaConfPath   = '/data/samba/smb.conf';

    public function __construct(Database $db) {
        $this->db = $db;
    }

    /**
     * Helper to get the primary IP of the host
     */
    private function getHostIPs() {
        $ips = ['v4' => '127.0.0.1', 'v6' => '::1'];
        
        // Execute hostname -I to get host IPs (since we are in network_mode host or have container IPs)
        $output = shell_exec("hostname -I");
        if ($output) {
            $parts = explode(' ', trim($output));
            foreach ($parts as $part) {
                $part = trim($part);
                if (filter_var($part, FILTER_VALIDATE_IP, FILTER_FLAG_IPV4)) {
                    if ($ips['v4'] === '127.0.0.1') {
                        $ips['v4'] = $part;
                    }
                } elseif (filter_var($part, FILTER_VALIDATE_IP, FILTER_FLAG_IPV6)) {
                    // Avoid link-local IPv6 addresses (fe80::) for primary setting if possible
                    if ($ips['v6'] === '::1' && strpos($part, 'fe80::') !== 0) {
                        $ips['v6'] = $part;
                    }
                }
            }
        }
        return $ips;
    }

    public function generateAll() {
        $this->generateBindConfig();
        $this->generateDnsmasqConfig();
        $this->generateChronyConfig();
        $this->generateSambaConfig();
    }

    public function generateBindConfig() {
        $settings = $this->db->getSettings();
        $domain = $settings['domain_name'] ?? 'lighting.local';
        $primaryDns = $settings['primary_dns'] ?? '8.8.8.8';
        $secondaryDns = $settings['secondary_dns'] ?? '1.1.1.1';

        // 1. Write named.conf.options
        $optionsContent = "options {\n";
        $optionsContent .= "    directory \"/var/cache/bind\";\n\n";
        $optionsContent .= "    forwarders {\n";
        if (!empty($primaryDns)) {
            $optionsContent .= "        " . $primaryDns . ";\n";
        }
        if (!empty($secondaryDns)) {
            $optionsContent .= "        " . $secondaryDns . ";\n";
        }
        $optionsContent .= "    };\n\n";
        $optionsContent .= "    dnssec-validation auto;\n";
        $optionsContent .= "    listen-on { any; };\n";
        $optionsContent .= "    listen-on-v6 { any; };\n";
        $optionsContent .= "    allow-query { any; };\n";
        $optionsContent .= "    allow-query-cache { any; };\n";
        $optionsContent .= "    recursion yes;\n";
        $optionsContent .= "};\n";

        file_put_contents($this->bindOptionsPath, $optionsContent);

        // 2. Write named.conf.local
        $localContent = "// Local zones configuration\n";
        $localContent .= "// Generated by Web Admin. DO NOT EDIT.\n\n";
        $localContent .= "zone \"" . $domain . "\" {\n";
        $localContent .= "    type master;\n";
        $localContent .= "    file \"/etc/bind/zones/db." . $domain . "\";\n";
        $localContent .= "};\n";

        file_put_contents($this->bindLocalPath, $localContent);

        // 3. Write zone file db.<domain>
        if (!file_exists($this->bindZonesDir)) {
            mkdir($this->bindZonesDir, 0777, true);
        }

        $hostIPs = $this->getHostIPs();
        $serial = time();

        $zoneContent = "\$TTL    604800\n";
        $zoneContent .= "@       IN      SOA     ns1." . $domain . ". admin." . $domain . ". (\n";
        $zoneContent .= "                              " . $serial . "         ; Serial\n";
        $zoneContent .= "                          604800         ; Refresh\n";
        $zoneContent .= "                           86400         ; Retry\n";
        $zoneContent .= "                         2419200         ; Expire\n";
        $zoneContent .= "                          604800 )       ; Negative Cache TTL\n";
        $zoneContent .= ";\n";
        $zoneContent .= "@       IN      NS      ns1." . $domain . ".\n";
        $zoneContent .= "ns1     IN      A       " . $hostIPs['v4'] . "\n";
        if ($hostIPs['v6'] !== '::1') {
            $zoneContent .= "ns1     IN      AAAA    " . $hostIPs['v6'] . "\n";
        }
        $zoneContent .= "\n; Custom records\n";

        // Query custom DNS records
        $pdo = $this->db->getConnection();
        $stmt = $pdo->query("SELECT hostname, ip_address, ip_type FROM dns_records");
        while ($row = $stmt->fetch()) {
            $zoneContent .= sprintf("%-15s IN      %-5s %s\n", $row['hostname'], $row['ip_type'], $row['ip_address']);
        }

        // Query DHCP reservations to automatically add DNS records for convenience
        $stmt = $pdo->query("SELECT hostname, ip_address, ip_type FROM dhcp_reservations");
        if ($stmt->rowCount() > 0) {
            $zoneContent .= "\n; DHCP Static Reservations\n";
            while ($row = $stmt->fetch()) {
                $type = ($row['ip_type'] === 'IPv6') ? 'AAAA' : 'A';
                $zoneContent .= sprintf("%-15s IN      %-5s %s\n", $row['hostname'], $type, $row['ip_address']);
            }
        }

        file_put_contents($this->bindZonesDir . '/db.' . $domain, $zoneContent);
    }

    public function generateDnsmasqConfig() {
        $settings = $this->db->getSettings();
        $dhcpSettings = $this->db->getDhcpSettings();
        $interface = $settings['dhcp_interface'] ?? '';
        $hostIPs = $this->getHostIPs();

        $content = "# dnsmasq DHCP configuration\n";
        $content .= "# Generated by Web Admin. DO NOT EDIT.\n\n";

        if (!empty($interface)) {
            $content .= "interface=" . $interface . "\n\n";
        }

        // DHCPv4 Config
        if ($dhcpSettings['v4_enabled']) {
            $content .= "# DHCPv4 settings\n";
            $content .= sprintf("dhcp-range=%s,%s,%s,%s\n", 
                $dhcpSettings['v4_range_start'],
                $dhcpSettings['v4_range_end'],
                $dhcpSettings['v4_netmask'],
                $dhcpSettings['v4_lease_time']
            );
            $content .= "dhcp-option=option:router," . $dhcpSettings['v4_gateway'] . "\n";
            
            // Advertise this host (running Bind9) as the DNS server
            $content .= "dhcp-option=option:dns-server," . $hostIPs['v4'] . "\n\n";
        }

        // DHCPv6 Config
        if ($dhcpSettings['v6_enabled']) {
            $content .= "# DHCPv6 settings\n";
            // Example: dhcp-range=fd00::100,fd00::200,64,12h
            $prefixLen = '64';
            if (strpos($dhcpSettings['v6_prefix'], '/') !== false) {
                $parts = explode('/', $dhcpSettings['v6_prefix']);
                $prefixLen = $parts[1];
            }
            $content .= sprintf("dhcp-range=%s,%s,%s,%s\n",
                $dhcpSettings['v6_range_start'],
                $dhcpSettings['v6_range_end'],
                $prefixLen,
                $dhcpSettings['v6_lease_time']
            );
            
            // Enable router advertisement
            $content .= "enable-ra\n";
            
            // Advertise host IPv6 as DNS server (fallback to link-local address or ::1 if empty)
            $dnsV6 = ($hostIPs['v6'] !== '::1') ? $hostIPs['v6'] : '::';
            $content .= "dhcp-option=option6:dns-server,[" . $dnsV6 . "]\n\n";
        }

        // Static IP Reservations
        $pdo = $this->db->getConnection();
        $stmt = $pdo->query("SELECT hostname, mac_address, ip_address, ip_type FROM dhcp_reservations");
        if ($stmt->rowCount() > 0) {
            $content .= "# Static DHCP leases\n";
            while ($row = $stmt->fetch()) {
                if ($row['ip_type'] === 'IPv6') {
                    $content .= sprintf("dhcp-host=%s,[%s],%s\n", $row['mac_address'], $row['ip_address'], $row['hostname']);
                } else {
                    $content .= sprintf("dhcp-host=%s,%s,%s\n", $row['mac_address'], $row['ip_address'], $row['hostname']);
                }
            }
        }

        // Ensure directories exist
        $dir = dirname($this->dnsmasqConfPath);
        if (!file_exists($dir)) {
            mkdir($dir, 0777, true);
        }

        file_put_contents($this->dnsmasqConfPath, $content);
    }

    public function generateChronyConfig() {
        $settings = $this->db->getSettings();
        $serversStr = $settings['ntp_servers'] ?? 'pool.ntp.org';
        $servers = array_map('trim', explode(',', $serversStr));

        $content = "# NTP chrony configuration\n";
        $content .= "# Generated by Web Admin. DO NOT EDIT.\n\n";

        foreach ($servers as $server) {
            if (!empty($server)) {
                $content .= "pool " . $server . " iburst\n";
            }
        }

        $content .= "\n";
        $content .= "allow all\n";
        $content .= "local stratum 10\n";
        $content .= "driftfile /var/lib/chrony/drift\n";
        $content .= "makestep 1.0 3\n";

        // Ensure directories exist
        $dir = dirname($this->chronyConfPath);
        if (!file_exists($dir)) {
            mkdir($dir, 0777, true);
        }

        file_put_contents($this->chronyConfPath, $content);
    }

    public function generateSambaConfig() {
        $content = "# Samba configuration\n";
        $content .= "# Generated by Web Admin. DO NOT EDIT.\n\n";
        $content .= "[global]\n";
        $content .= "   workgroup = WORKGROUP\n";
        $content .= "   server string = Lightbox Server\n";
        $content .= "   server role = standalone server\n";
        $content .= "   security = user\n";
        $content .= "   map to guest = Bad User\n";
        $content .= "   dns proxy = no\n";
        $content .= "   log file = /var/log/samba/log.%m\n";
        $content .= "   max log size = 1000\n";
        $content .= "   server min protocol = SMB2\n";
        $content .= "   server max protocol = SMB3\n";
        $content .= "   usershare allow guests = yes\n\n";

        // Fetch shares
        $pdo = $this->db->getConnection();
        $stmt = $pdo->query("SELECT share_name, share_path, writable, guest_ok, description FROM samba_shares");
        while ($row = $stmt->fetch()) {
            $content .= "[" . $row['share_name'] . "]\n";
            $content .= "   comment = " . $row['description'] . "\n";
            $content .= "   path = " . $row['share_path'] . "\n";
            $content .= "   writable = " . ($row['writable'] ? 'yes' : 'no') . "\n";
            $content .= "   guest ok = " . ($row['guest_ok'] ? 'yes' : 'no') . "\n";
            $content .= "   guest only = " . ($row['guest_ok'] ? 'yes' : 'no') . "\n";
            $content .= "   force user = nobody\n";
            $content .= "   create mask = 0777\n";
            $content .= "   directory mask = 0777\n";
            $content .= "   browseable = yes\n\n";

            // Ensure directories exist on host (shared volume path inside container is /shares/...)
            // Wait, we need to create the directory inside the container if it doesn't exist
            if (!file_exists($row['share_path'])) {
                mkdir($row['share_path'], 0777, true);
                chmod($row['share_path'], 0777);
            }
        }

        // Ensure directories exist
        $dir = dirname($this->sambaConfPath);
        if (!file_exists($dir)) {
            mkdir($dir, 0777, true);
        }

        file_put_contents($this->sambaConfPath, $content);
    }
}
