@version: 4.2

options {
    time-reap(30);
    mark-freq(0);
    keep-hostname(yes);
    chain-hostnames(no);
    log-fifo-size(1000);
};

source s_udp {
    udp(ip(0.0.0.0) port(514));
};

source s_tcp {
    tcp(ip(0.0.0.0) port(514) max-connections(50));
};

destination d_messages {
    file(
        "/data/syslog/messages.log"
        template("${ISODATE} ${HOST} ${PROGRAM}[${PID}]: ${MESSAGE}\n")
        create-dirs(yes)
        perm(0644)
        dir-perm(0755)
    );
};

log {
    source(s_udp);
    source(s_tcp);
    destination(d_messages);
};
